---
- name: Load playbooks
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - config.yml
  tasks:
    - name: Include RHEL tasks
      ansible.builtin.import_tasks: tasks/rhel.yaml
      when: ansible_os_family == 'RedHat'

    - name: Include Debian tasks
      ansible.builtin.import_tasks: tasks/debian.yaml
      when: ansible_os_family == 'Debian'

